Add three letter abbreviations to ProteinAlphabet
dotnetbio/bio pull request #38
Opened 2018-01-24 19:45 UTC by acesnik

2018-01-25 03:11 UTC, evolvedmicrobe requested changes
Hey Anthony,

Welcome to .NET Bio and thanks for submitting the pull request!  I looked it over, and am not entirely sure I get what the intention was here so left some comments/questions for you.  Adding three letter codes certainly seems useful though so I am glad to see that in here.  Anyway, let me know your responses to comments and we'll go from there!

Cheers,
Nigel

2018-01-25 20:57 UTC, acesnik commented on Source/Bio.Core/AmbiguousProteinAlphabet.cs
> +            AddAminoAcid(this.X, "Unx", "Undetermined or atypical", (byte)'x');
Ah! Thanks for catching that; those were informal abbreviations. I updated them to Xaa, etc. in the latest push.

2018-01-25 20:58 UTC, acesnik commented on Source/Bio.Core/ProteinAlphabet.cs
> +        private readonly Dictionary<byte, string> threeLetterAbbreviationMap = new Dictionary<byte, string>();
Good point on the variable being private. My intention was to allow the user to get 3-letter abbreviations from a symbol, and vice versa. I added get methods to satisfy that intention.

2018-01-25 21:20 UTC, acesnik commented
Thanks for the welcome! I responded to your comments and made some changes accordingly.

2018-01-27 02:56 UTC, evolvedmicrobe commented
Looks good to me, congrats on first commit!

Going forward, you may find it easier to name branches based on the types of feature they have (e.g. `git checkout -b threeletter` to make a branch for this feature), and it can also be nice to squash your commits into one later on.  For a first go though, no need to worry about this.

All the best,
Nigel

2018-01-27 02:56 UTC, evolvedmicrobe approved these changes

2018-01-27 02:56 UTC, merged

2018-01-30 20:56 UTC, acesnik commented
Thanks! 

Sounds good. I'll make feature branches and squash commits in the future.

Anthony